name: Update README with Weekly Reports

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Weekly Reports List
        run: |
          echo "## 📌 Latest Weekly Reports" > latest_reports.md
          find Spring-2025 -type f -name "*.md" | sort -r | while read file; do
            TITLE=$(awk 'NR==1{sub(/^# /, ""); print; exit}' "$file" | sed 's/^ *//;s/ *$//')
            [ -z "$TITLE" ] && TITLE="$file"
            echo "- [${TITLE}](${file})" >> latest_reports.md
          done
            echo "" >> latest_reports.md
          awk '/## 📌 Latest Weekly Reports/{exit} {print}' README.md > temp_start.md
          awk '/## 📌 Purpose/{flag=1} flag' README.md >> temp_end.md
          cat temp_start.md latest_reports.md temp_end.md > README.md
          rm temp_start.md temp_end.md latest_reports.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || (git commit -m "Auto-update README with latest reports" && git push)

  create-next-week-folder:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create next week's folder if needed
        run: |
          LAST_WEEK=$(find Spring-2025 -type d -name "Week-*" | sort -V | tail -n1 | awk '{print $NF}')
          NEXT_WEEK=$((LAST_WEEK + 1))
          if [ -n "$(ls -A "Spring-2025/Week-$LAST_WEEK"/*.md 2>/dev/null)" ]; then
            mkdir -p "Spring-2025/Week-$NEXT_WEEK"
            git add "Spring-2025/Week-$NEXT_WEEK"
          fi

      - name: Commit and push new week folder
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git diff --cached --quiet || (git commit -m "Create folder for Week $NEXT_WEEK" && git push)